{
	"slider":{
		"sliderId": 1,
		"sliderName": "Main Slider",
		"sliderType": "fixed",
		"responsive": false,
		"width": 1430,
		"height": 600,
		"theme": "forest",
		"arrows":
		{
			"status":true,
			"type":"fullarrow",
			"size":"medium",
			"primaryColor":"#FFFFFF",
			"secondaryColor":"#000000",
			"descriptionFamily":"Arial",
			"descriptionWeight":"inherit",
			"descriptionSize":"14",
			"descriptionSizing":"px",
			"descriptionColor":"#666666",
			"countFamily":"Arial",
			"countWeight":"normal",
			"countSize":"12",
			"countSizing":"px",
			"countColor":"#FFFFFF"
		},
		"pager":
		{
			"status":true,
			"type":"fill_up",
			"position":"bottom_center",
			"primaryColor":"white",
			"secondaryColor":"white",
			"size":10,
			"transparency":0.5
		},
		"video":
		{
			"autoPlay":true,
			"autoPause":true
		},
		"timer":
		{
			"status":false,
			"type":"circle_load",
			"position":"bottom",
			"primaryColor":"#000000",
			"secondaryColor":"#FFFFFF",
			"transparency":0.7,
			"hoverStop":true,
			"autoPlay":true
		},
		"border":
		{
			"status":false,
			"borderSize":2,
			"borderType":"solid",
			"borderColor":"#666",					
			"borderRadius":false,
			"borderRadiusTopLeft":10,
			"borderRadiusTopRight":10,
			"borderRadiusBottomLeft":10,
			"borderRadiusBottomRight":10
		},
		"button":
		{
			"type":"button_twist",
			"primaryColor":"#FFFFFF",
			"secondaryColor":"#000000",
			"transparency":0.3,
			"buttonFamily":"Arial",
			"buttonWeight":"bold",
			"buttonSize":"12",
			"buttonSizing":"px",
			"buttonColor":"#CC0000"
		},
		"slides":[]
	}    
}